### ISSUE TITLE
Intial setup errors & friction

### ISSUE THREAD

**Issue by clintonhalpin** [gavinmcfarland/plugma#19]
Tried setting up plugma for first time I ran into a few of issues which I was able to workaround. I was using react, typescript on node v.20

1. Running `npm install`, gives error — **Doesn't exist "@types/react-dom": "^18.3.1"**
- Fix: Installed `@types/react-dom@^18.3.0`

2. Running `plugma dev` gives error  — **Failed to load url /src/ui.jsx (resolved id: /src/ui.jsx). Does the file exist? (x2)**
- Fix: Renamed `ui.tsx` to `ui.jsx` (which might not be right)

I could try and fix / unless I'm doing something wrong!

**Comment by gavinmcfarland** [comment]
Thank you @clintonhalpin!

It looks like React pulled the latest version of their type package. I've rolled back the template to use the previous version now. Thank you.

Regarding your second issue, could you let me know if this was with the non-TypeScript version or the TypeScript version? I'm aware of an issue that I fixed yesterday, where `ui.jsx` was importing `App.tsx` and it should have been `App.jsx`. But I can't recreate the error you're experiencing. If you're using the TypeScript version, it should be using `ui.tsx`. If you let me know, I'll look into it more.

I really appreciate your feedback because I'm not always using all the frameworks at the same time.

**Comment by clintonhalpin** [comment]
@gavinmcfarland I was using the Typescript version!

Thanks for quick reply here.

**Comment by gavinmcfarland** [comment]
I knew it was, it just seemed really strange that you got that issue/error.

If you rename the file to `uit.tsx` and then update your `manifest` field or file to `"ui": "src/ui.tsx"`, it should be good. Technically, it probably doesn't matter much because it's just where the UI gets mounted/rendered.

Thanks again for highlighting the friction you encountered, much appreciated!
